custom_theme <-
structure(list(axis.title.x = structure(list(family = NULL, face = "bold", 
    size = 14, colour = "#08415C", fill = NULL, box.colour = NULL, 
    linetype = NULL, linewidth = NULL, hjust = NULL, vjust = NULL, 
    halign = NULL, valign = NULL, angle = NULL, lineheight = NULL, 
    margin = NULL, padding = NULL, r = NULL, align_widths = NULL, 
    align_heights = NULL, rotate_margins = NULL, debug = FALSE, 
    inherit.blank = FALSE), class = c("element_markdown", "element_text", 
"element")), axis.title.y = structure(list(family = NULL, face = "bold", 
    size = 14, colour = "#08415C", fill = NULL, box.colour = NULL, 
    linetype = NULL, linewidth = NULL, hjust = NULL, vjust = NULL, 
    halign = NULL, valign = NULL, angle = NULL, lineheight = NULL, 
    margin = NULL, padding = NULL, r = NULL, align_widths = NULL, 
    align_heights = NULL, rotate_margins = NULL, debug = FALSE, 
    inherit.blank = FALSE), class = c("element_markdown", "element_text", 
"element")), axis.text.x = structure(list(family = NULL, face = NULL, 
    size = 12, colour = "#08415C", fill = NULL, box.colour = NULL, 
    linetype = NULL, linewidth = NULL, hjust = NULL, vjust = NULL, 
    halign = NULL, valign = NULL, angle = NULL, lineheight = NULL, 
    margin = NULL, padding = NULL, r = NULL, align_widths = NULL, 
    align_heights = NULL, rotate_margins = NULL, debug = FALSE, 
    inherit.blank = FALSE), class = c("element_markdown", "element_text", 
"element")), axis.text.y = structure(list(family = NULL, face = NULL, 
    size = 12, colour = "#08415C", fill = NULL, box.colour = NULL, 
    linetype = NULL, linewidth = NULL, hjust = NULL, vjust = NULL, 
    halign = NULL, valign = NULL, angle = NULL, lineheight = NULL, 
    margin = NULL, padding = NULL, r = NULL, align_widths = NULL, 
    align_heights = NULL, rotate_margins = NULL, debug = FALSE, 
    inherit.blank = FALSE), class = c("element_markdown", "element_text", 
"element")), legend.text = structure(list(family = NULL, face = NULL, 
    size = 12, colour = "#08415C", fill = NULL, box.colour = NULL, 
    linetype = NULL, linewidth = NULL, hjust = NULL, vjust = NULL, 
    halign = NULL, valign = NULL, angle = NULL, lineheight = NULL, 
    margin = NULL, padding = NULL, r = NULL, align_widths = NULL, 
    align_heights = NULL, rotate_margins = NULL, debug = FALSE, 
    inherit.blank = FALSE), class = c("element_markdown", "element_text", 
"element")), legend.title = structure(list(family = NULL, face = NULL, 
    size = 12, colour = "#08415C", fill = NULL, box.colour = NULL, 
    linetype = NULL, linewidth = NULL, hjust = NULL, vjust = NULL, 
    halign = NULL, valign = NULL, angle = NULL, lineheight = NULL, 
    margin = NULL, padding = NULL, r = NULL, align_widths = NULL, 
    align_heights = NULL, rotate_margins = NULL, debug = FALSE, 
    inherit.blank = FALSE), class = c("element_markdown", "element_text", 
"element")), legend.position = "none", panel.background = structure(list(
    fill = "white", colour = NULL, linewidth = NULL, linetype = NULL, 
    inherit.blank = FALSE), class = c("element_rect", "element"
)), panel.border = structure(list(fill = NA, colour = "#08415C", 
    linewidth = 1, linetype = NULL, inherit.blank = FALSE), class = c("element_rect", 
"element")), panel.grid.major = structure(list(colour = "gray", 
    linewidth = 0.5, linetype = NULL, lineend = NULL, arrow = FALSE, 
    inherit.blank = FALSE), class = c("element_line", "element"
)), panel.grid.minor = structure(list(colour = "lightgray", linewidth = 0.25, 
    linetype = NULL, lineend = NULL, arrow = FALSE, inherit.blank = FALSE), class = c("element_line", 
"element")), plot.background = structure(list(fill = "white", 
    colour = NULL, linewidth = NULL, linetype = NULL, inherit.blank = FALSE), class = c("element_rect", 
"element")), plot.title = structure(list(family = NULL, face = "bold", 
    size = 16, colour = "#08415C", fill = NULL, box.colour = NULL, 
    linetype = NULL, linewidth = NULL, hjust = 0.5, vjust = NULL, 
    halign = NULL, valign = NULL, angle = NULL, lineheight = NULL, 
    margin = NULL, padding = NULL, r = NULL, align_widths = NULL, 
    align_heights = NULL, rotate_margins = NULL, debug = FALSE, 
    inherit.blank = FALSE), class = c("element_markdown", "element_text", 
"element")), plot.subtitle = structure(list(family = NULL, face = NULL, 
    size = 14, colour = "#08415C", fill = NULL, box.colour = NULL, 
    linetype = NULL, linewidth = NULL, hjust = 0.5, vjust = NULL, 
    halign = NULL, valign = NULL, angle = NULL, lineheight = NULL, 
    margin = NULL, padding = NULL, r = NULL, align_widths = NULL, 
    align_heights = NULL, rotate_margins = NULL, debug = FALSE, 
    inherit.blank = FALSE), class = c("element_markdown", "element_text", 
"element")), plot.margin = structure(c(10, 10, 10, 10), unit = 8L, class = c("margin", 
"simpleUnit", "unit", "unit_v2")), strip.background = structure(list(), class = c("element_blank", 
"element")), strip.placement = "outside", strip.text.x = structure(list(
    family = NULL, face = "bold", size = 12, colour = "#08415C", 
    fill = NULL, box.colour = NULL, linetype = NULL, linewidth = NULL, 
    hjust = NULL, vjust = NULL, halign = NULL, valign = NULL, 
    angle = NULL, lineheight = NULL, margin = NULL, padding = NULL, 
    r = NULL, align_widths = NULL, align_heights = NULL, rotate_margins = NULL, 
    debug = FALSE, inherit.blank = FALSE), class = c("element_markdown", 
"element_text", "element")), strip.text.y = structure(list(family = NULL, 
    face = "bold", size = 14, colour = "#08415C", fill = NULL, 
    box.colour = NULL, linetype = NULL, linewidth = NULL, hjust = NULL, 
    vjust = NULL, halign = NULL, valign = NULL, angle = NULL, 
    lineheight = NULL, margin = NULL, padding = NULL, r = NULL, 
    align_widths = NULL, align_heights = NULL, rotate_margins = NULL, 
    debug = FALSE, inherit.blank = FALSE), class = c("element_markdown", 
"element_text", "element"))), class = c("theme", "gg"), complete = FALSE, validate = TRUE)
